version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
deployment:
     staging:
       branch: master
       commands:
         - git remote add heroku git@heroku.com:bodotika.git
         - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
         - cd ../../.. && git subtree push --prefix https://github.com/lelajour/Bodotika heroku master
